name: WoolBattle
main: Fludixx\WoolBattle\Main
version: 1.1.3
api: [3.0.0-ALPHA12, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5]
author: Fludixx
description: WoolBatlle Plugin for pmmp
website: https://github.com/Fludixx/
commands:
    wbgeteq:
        description: "Gives you Woolbattle Equip"
    eq:
        description: "WoolBattle EQ"
    cords:
        description: "Cords -> Woolbattle"
    spectate:
        description: "Spectate -> Woolbattle"
    lobby:
        description: "Teleport to Woolbattle Lobby"
