name: Woolbattle
description: "Woolbattle Plugin for Pocketmine"
version: 2.0
author: Fludixx
website: github.com/Fludixx/WoolBattle
api: [3.0.0, 4.0.0]
main: Fludixx\Woolbattle\Woolbattle
commands:
  woolbattle:
    description: "Woolbattle Command"
  leave:
    description: "Leave a match"
  elo:
    description: "Elo Command"
