---
x1: -3
y1: 21
z1: 30
x2: -3
y2: 21
z2: -12
spawnx: 87
spawny: 65
spawnz: -72
usew1: false
usew2: false
usew3: false
usew4: false
usew5: false
usew6: false
usew7: false
usew8: false
usew9: false
usew10: false
arenas:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
...
